version: '3.3'

services:

  node:
    build:
      context: ./node
      args:
        - NODE_VERSION=latest
        - PROJECT_PATH=/opt/app/
        - NODE_ENV=production
        - PORT=3000
        - YARN=false
    volumes:
      - ../:/opt/app
    entrypoint: run-nodock "npm start"
    tty: true

  postgresql:
    build:
      context: ./postgresql
      args:
        - POSTGRES_USER=beam
        - POSTGRES_PASSWORD=beambadaboum
        - POSTGRES_DB=beam
    volumes:
      - ./data/postgresql/:/var/lib/postgresql
    expose:
      - "5432"

  nginx:
    build:
      context: ./nginx
      args:
        - WEB_REVERSE_PROXY_PORT=3000
        - WEB_SSL=false
        - SELF_SIGNED=false
        - NO_DEFAULT=false
    volumes:
      - ./data/logs/nginx/:/var/log/nginx
      - ./certbot/certs/:/var/certs
    ports:
      - "80:80"
      - "443:443"
    tty: true

  certbot:
    build:
      context: ./.compose/certbot
    links:
      - nginx
    volumes:
      - ./certbot/letsencrypt/:/var/www/letsencrypt
      - ./certbot/certs/:/var/certs
